[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
via_ir = true
optimizer = true
optimizer_runs = 200

# Monad Testnet Configuration
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${MONAD_ETHERSCAN_API_KEY}", url = "https://testnet.monadexplorer.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
